services:
  database:
    container_name: neesowork-db
    build: db
    ports:
      - '3306:3306'
    env_file:
        'mysql.env'
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  backend:
    container_name: neesowork-backend
    build: backend
    ports:
      - '8000:8000'
    depends_on:
        database:
            condition: service_healthy

  frontend:
    container_name: neesowork-frontend
    build: frontend
    ports:
      - '80:80'
